service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  getNativeBalance:
    handler: functions/getNativeBalance.handler
  getWalletNfts:
    handler: functions/getWalletNfts.handler
